apiVersion: v1

kind: Service

metadata:
  name: httpd-service
  namespace: project1

spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
      protocol: TCP
      nodePort: 30007
  selector:
    app: httpd-web
