apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: httpd-pvc
  namespace: project1
spec:
  storageClassName: http-ssd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
---
# How do we want it implemented
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: http-ssd
  namespace: project1
provisioner: cluster.local/http-ssd-nfs-subdir-external-provisioner
parameters:
  type: pd-standard
